export const roomTypeConst = [
    {
        type: "single-room",
        "Custom Room Name": "",
        "Allowed Guests": 0,
        "Number of Rooms": 0,
        "Published Rate (excl. VAT)": 0,
        "Agency Rate (excl. VAT)": 0,
    },
    {
        type: "double-room",
        "Custom Room Name": "",
        "Allowed Guests": 0,
        "Number of Rooms": 0,
        "Published Rate (excl. VAT)": 0,
        "Agency Rate (excl. VAT)": 0,
    },
    {
        type: "suite",
        "Custom Room Name": "",
        "Allowed Guests": 0,
        "Number of Rooms": 0,
        "Published Rate (excl. VAT)": 0,
        "Agency Rate (excl. VAT)": 0,
    },
    {
        type: "family-room",
        "Custom Room Name": "",
        "Allowed Guests": 0,
        "Number of Rooms": 0,
        "Published Rate (excl. VAT)": 0,
        "Agency Rate (excl. VAT)": 0,
    },
    {
        type: "deluxe-room",
        "Custom Room Name": "",
        "Allowed Guests": 0,
        "Number of Rooms": 0,
        "Published Rate (excl. VAT)": 0,
        "Agency Rate (excl. VAT)": 0,
    },
    {
        type: "superior-room",
        "Custom Room Name": "",
        "Allowed Guests": 0,
        "Number of Rooms": 0,
        "Published Rate (excl. VAT)": 0,
        "Agency Rate (excl. VAT)": 0,
    },
];
